
menu:
  categories:
    - name: tables
      subcategories:
        - name: all
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
            - name: B14
            - name: B15
            - name: B15
            - name: B16
            - name: B17
            - name: B18
    - name: food
      subcategories:
        - name: dinner
          items: 
            - name: warm olives
              price: 5
            - name: marcona almonds
              price: 6
            - name: walnut pesto
              price: 5
            - name: mussels
              price: 7
            - name: smoked anchovies
              price: 6
            - {name: patatas bravas, price: 5}
            - {name: meatballs, price: 8}
            - {name: roasted chorizo, price: 6}
            - {name: marrow bones, price: 6}
            - {name: tapa polenta mushrooms , price: 7}
            - {name: plate polenta mushrooms, price: 12}
            - {name: oxtail, price: 9}
            - {name: green caprese, price: 7}
            - {name: beet orange, price: 5}
            - {name: grilled calabrian, price: 9}
            - {name: pulled beef, price: 8}
            - {name: short rib, price: 18}
            - {name: chicken, price: 16}
            - {name: mini_panini, price: 7}
            - {name: beef_slider , price: 7}
        - name: boards
          items: 
            - name: 3-board
              price: 15
            - name: 5-board
              price: 22
            - name: italian board
              price: 26
            - name: spaish board
              price: 26
            - name: french board
              price: 26
            - {name: manchego , price: 0}
            - {name: granny goat, price: 0}
            - {name: torta de cesar, price: 0}
            - {name: comte, price: 0}
            - {name: daffinois, price: 0}
            - {name: fourme dambert, price: 0}
            - {name: petit basque, price: 0}
            - {name: tallaegio, price: 0}
            - {name: paive, price: 0}
            - {name: pecorino tartufo, price: 0}
            - {name: seranno ham, price: 0}
            - {name: prosciutto, price: 0}
            - {name: lomo, price: 0}
            - {name: hot capicolla, price: 0}
            - {name: chorizo, price: 0}
            - {name: rosette de lyon, price: 0}
            - {name: cacciatorini, price: 0}
            - {name: country pate, price: 0}
        - name: dessert_etc
          items: 
            - {name: pelligrino, price: 6}
            - {name: coffee, price: 3}
            - {name: tea, price: 3}
            - {name: soda, price: 3}
            - {name: panacotta, price: 5}
            - {name: chocolate, price: 5}
            - {name: cktail7, price: 7}
            - {name: cktail10, price: 10}
