
menu:
  categories:
    - name: tables
      subcategories:
        - name: all
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
            - name: B14
            - name: B15
            - name: B16
            - name: B17
            - name: F1
            - name: F2
            - name: F3
            - name: F4
            - name: F5
            - name: O1
            - name: O2
            - name: O3
            - name: O4
            - name: O5
        - name: staff
          items: 
            - name: JWK
            - name: DL
            - name: LQK
            - name: JL
            - name: DS
            - name: JA
            - name: MN
            - name: DW
            - name: DP
            - name: RP
    - name: food
      subcategories:
        - name: dinner
          items: 
            - {name: warm olives, price: 5}
            - {name: marcona almonds, price: 6}
            - {name: walnut pesto, price: 6}
            - {name: anchovy, price: 6}
            #- {name: peppers, price: 7}
            #- {name: corn, price: 5}
            - {name: summer harvest, price: 8}
            - {name: cauli, price: 7}
            #- {name: mussels, price: 7}
            - {name: salmon, price: 7}
            #- {name: prawn, price: 10}
            - {name: octopus, price: 12}
            - {name: burrata , price: 14}
            - {name: patatas bravas, price: 5}
            - {name: meatballs, price: 8}
            - {name: empanada, price: 7}
            - {name: mini panini , price: 7}
            - {name: marrow bones, price: 8}
            #- {name: french onion, price: 7}
            - {name: gratin, price: 7}
            - {name: bocadillo, price: 8}
            - {name: polenta tapa, price: 7}
            - {name: polenta plate, price: 12}
            - {name: oxtail, price: 10}
            - {name: chicken, price: 18}
            #- {name: truffle rib, price: 19}
            - {name: bread, price: 3}
        - name: boards
          items: 
            - name: 1-board
              price: 7
            - name: 3-board
              price: 16
            - name: 5-board
              price: 23
            - name: italian board
              price: 27
            - name: spanish board
              price: 27
            - name: french board
              price: 27
            - {name: manchego , price: 0}
            - {name: cana de cabra, price: 0}
            - {name: campo de montalban, price: 0}
            - {name: tallegio, price: 0}
            - {name: piave, price: 0}
            - {name: pecorino tartufo, price: 0}
            - {name: daffinois, price: 0}
            - {name: fourme dambert, price: 0}
            - {name: capri, price: 0}
            - {name: seranno ham, price: 0}
            - {name: lomo, price: 0}
            - {name: chorizo, price: 0}
            - {name: prosciutto, price: 0}
            - {name: hot capicolla, price: 0}
            - {name: salametto, price: 0}
            - {name: jambon, price: 0}
            - {name: rosette de lyon, price: 0}
            - {name: pate, price: 0}
        - name: dessert_etc
          items: 
            - {name: pelligrino, price: 6}
            - {name: coffee, price: 3}
            - {name: tea, price: 3}
            - {name: soda, price: 3}
            - {name: seltzer, price: 2}
            - {name: panacotta, price: 5}
            - {name: chocolate, price: 5}
            - {name: cktail5, price: 5}
            - {name: cktail7, price: 7}
            - {name: cktail10, price: 10}
            - {name: cktail12, price: 12}
            - {name: liquor flight, price: 16}
            - {name: red flight, price: 16}
            - {name: white flight, price: 10}
            - {name: gift25, price: 25}
            - {name: gift40, price: 40}
            - {name: gift50, price: 50}
            - {name: gift75, price: 75}
            - {name: gift100, price: 100}
        - name: specials
          items: 
            - {name: discount, price: -1}
            - {name: extras, price: 1}
            - {name: special3, price: 3}
            - {name: special4, price: 4}
            - {name: special5, price: 5}
            - {name: special6, price: 6}
            - {name: special7, price: 7}
            - {name: special8, price: 8}
            - {name: special9, price: 9}
            - {name: special10, price: 10}
            - {name: special11, price: 11}
            - {name: special12, price: 12}
            - {name: special13, price: 13}
            - {name: special14, price: 14}
            - {name: special15, price: 15}
        - name: lunch
          items: 
            - {name: salmon_san, price: 8}
            - {name: burrata_san, price: 9}
            - {name: prosciutto_san, price: 10}
            - {name: spanish_san, price: 9}
            - {name: soppresatta_san, price: 7}
            - {name: cuban_san, price: 9}
            - {name: goat_mush_san, price: 8}
            - {name: pork_san, price: 9}
            - {name: beef_san, price: 10}
            - {name: ceasar_lun, price: 8}
            - {name: beet_ora_lun, price: 6}
            - {name: copa_goat_lun, price: 9}
            - {name: soup, price: 6}
        #- name: breakfast
        #  items: 
        #    - {name: bacon egg, price: 6}
        #    - {name: yogurt, price: 4}
        #    - {name: masc fig, price: 3}
        #    - {name: pb strawberry, price: 3}
        #    - {name: nuttella zest, price: 3}
        #    - {name: jamon cheese, price: 5}
        #    - {name: prosciut cheese, price: 5}
        #    - {name: breakfast tea, price: 3}
        #    - {name: coffee, price: 3}
        #    - {name: hot choco, price: 3}
