
DELIVERY_STATUS_HELD = 0; MIN_DELIVERY_STATUS = DELIVERY_STATUS_HELD;
DELIVERY_STATUS_RELEASED = 1;
DELIVERY_STATUS_READY = 2;
DELIVERY_STATUS_DELIVERED = 3; MAX_DELIVERY_STATUS = DELIVERY_STATUS_DELIVERED;
