
menu:
  categories:
    - name: tables
      subcategories:
        - name: floor
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: 10
            - name: 11
            - name: 12
            - name: 13
        - name: bar
          items: 
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
        - name: other
          items: 
            - name: O1
            - name: O2
            - name: O3
            - name: O4
            - name: O5
            - name: O6
            - name: O7
            - name: TEST1
            - name: TEST2
        - name: takeout
          items: 
            - name: T1 
            - name: T2
            - name: T3
            - name: T4
            - name: T5
    - name: food
      subcategories:
        - name: dinner
          items: 
            - {name: warm olives, price: 5}
            - {name: marcona almonds, price: 5}
            - {name: anchovy, price: 6}
            - {name: caesar , price: 9}
            - {name: burrata , price: 14}
            - {name: patatas bravas, price: 6}
            - {name: peppers, price: 9}
            - {name: carney corn, price: 8}
            - {name: sprouts, price: 12}
            - {name: scallops, price: 14}
            - {name: foie gras, price: 16}
            - {name: sweetbreads , price: 14}
            - {name: marrow bones, price: 8}
            - {name: pulpo, price: 14}
            - {name: bocadillo, price: 9}
            - {name: corn bisque, price: 8}
            - {name: duck, price: 16}
            - {name: beef chorizo, price: 10}
            - {name: steak, price: 21}
            - {name: panacotta, price: 7}
            - {name: chocolate, price: 7}
            - {name: apple crisp, price: 7}
            - {name: special, price: 0}
            - {name: bread, price: 3}
            - {name: special note, add_on_price: 0}
        - name: boards
          items: 
            - {name: taste of spain, price: 12}
            - name: 1-board
              price: 7
            - name: 3-board
              price: 18
            - name: 5-board
              price: 28
            - name: 6-board
              price: 32
            - name: italian board
              price: 32
            - name: spanish board
              price: 32
            - name: mixed cheese board
              price: 32
            - {name: manchego , add_on_price: 0}
            - {name: cana de cabra, add_on_price: 0}
            - {name: campo de montalban, add_on_price: 0}
            - {name: rustico, add_on_price: 0}
            - {name: piave, add_on_price: 0}
            - {name: pecorino tartufo, add_on_price: 0}
            - {name: daffinois, add_on_price: 0}
            - {name: sao jorge, add_on_price: 0}
            - {name: blue cheese, add_on_price: 0}
            #- {name: gruyere, add_on_price: 0}
            - {name: queso sudado, add_on_price: 0}
            - {name: gouda, add_on_price: 0}
            #- {name: capri, add_on_price: 0}
            - {name: seranno ham, add_on_price: 0}
            - {name: lomo, add_on_price: 0}
            - {name: chorizo, add_on_price: 0}
            - {name: prosciutto, add_on_price: 0}
            - {name: hot capicolla, add_on_price: 0}
            - {name: felino, add_on_price: 0}
            - {name: pata negra, add_on_price: 15}
            #- {name: rosette de lyon, add_on_price: 0}
            - {name: extra fig, add_on_price: 2}
            - name: add-on
              add_on_price: 5
            - name: to-go-on-board
              add_on_price: 0
            - {name: special note, add_on_price: 0}
        - name: allergy
          items: 
            - {name: gluten allergy, price: 0}
            - {name: nut allergy, price: 0}
            - {name: shellfish allergy, price: 0}
            - {name: egg allergy, price: 0}
            - {name: special allergy, price: 0}
        - name: misc
          items: 
            - {name: special event, price: 120}
            - {name: gift, price: 50}
            - {name: gratuity18, price: 18}
            - {name: gratuity20, price: 20}
            - {name: gratuity special, price: 0}
            - {name: tax-free special, price: 0}
            - {name: corkage fee, price: 10}
        - name: lunch
          items: 
            - {name: american burger, price: 15}
            - {name: spanish burger, price: 14}
            - {name: italian burger, price: 14}
            #- {name: lunch special, price: 9}
            #- {name: special tomato soup, price: 0}

            #- {name: half prosciutto san, price: 0}
            #- {name: half spanish ham and cheese, price: 0}
            #- {name: half eggplant, price: 0}
            #- {name: half bcadillo, price: 0}

            #- {name: half taleggio panini, price: 0}
            #- {name: half soppresatta panini, price: 0}
            #- {name: half copa cubano, price: 0}
            #- {name: half goat mush san, price: 0}

            - {name: prosciutto san, price: 10}
            - {name: spanish ham and cheese, price: 9}
            - {name: eggplant, price: 7}
            - {name: bocadillo, price: 9}
            - {name: chorizo san, price: 12}
            - {name: daffinois panini, price: 10}
            - {name: soppresatta panini, price: 9}
            - {name: copa cubano, price: 11}
            - {name: goat mush san, price: 8}
            - {name: caesar, price: 9}
            - {name: burrata, price: 14}
            - {name: house salad, price: 8}
            - {name: tomato soup and cheesy toast, price: 7}
            - {name: corn bisque, price: 8}

            - {name: anchovy, price: 6}
            - {name: patatas, price: 6}
            - {name: scallops, price: 14}
            - {name: foie gras, price: 16}
            - {name: peppers, price: 9}
            - {name: bread, price: 3}
            - {name: special note, add_on_price: 0}
        - name: brunch 
          items: 
            - {name: bloomfield, price: 12}
            - {name: scramble, price: 8}
            - {name: frittata verde, price: 9}
            - {name: french toast, price: 8}
            - {name: bacon, price: 5}
            - {name: american burger, price: 15}
            - {name: spanish burger, price: 14}
            - {name: italian burger, price: 14}
            - {name: daffinois panini, price: 10}
            - {name: sopressata panini, price: 9}
            - {name: copa cubano, price: 11}
            - {name: goat cheese panini, price: 8}
            - {name: cesar, price: 9}
            - {name: burrata salad, price: 14}
            - {name: house salad, price: 8}
            - {name: smoked anchovies, price: 6}
            - {name: patatas bravas, price: 6}
            - {name: ham cheese toast, price: 8}
            - {name: peppers, price: 9}
            - {name: bocadillo, price: 9}
            - {name: bread, price: 3}
            - {name: coffee, price: 4}
            - {name: decaf, price: 4}
            - {name: iced tea, price: 3}
            - {name: english breakfast, price: 4}
            - {name: jasmin tea, price: 4}
            - {name: paris tea, price: 4}
            - {name: chamomile tea, price: 4}
            - {name: special note, add_on_price: 0}
    - name: bev
      subcategories:
        - name: coffee & tea
          items: 
            - {name: colombia, price: 4}
            - {name: decaf, price: 4}
            - {name: regular tea, price: 3}
            - {name: green jasmin, price: 4}
            - {name: ceylon tea, price: 4}
            - {name: paris tea, price: 4}
            - {name: chomomile, price: 4}
            - {name: iced unsweet tea, price: 3}
            - {name: iced sweet tea, price: 3}
        - name: cocktails 
          items: 
            - {name: special cocktail, price: 12}
            - {name: happy_hour5, price: 5}
            - {name: glass red sangria, price: 8}
            - {name: glass white sangria, price: 8}
            - {name: jar red sangria, price: 28}
            - {name: jar white sangria, price: 28}
            - {name: red flight, price: 16}
            - {name: white flight, price: 16}
            - {name: bubbly flight, price: 16}
            - {name: amaro lucano, price: 6}
            - {name: bellini jar, price: 25}
            - {name: bellini, price: 7}
            - {name: bloody maria jar, price: 36}
            - {name: bloody maria, price: 9}
            - {name: bloody mary, price: 9}
            - {name: cafe amaretto, price: 8}
            - {name: cascara sweet tea, price: 10}
            - {name: cosmo, price: 10}
            - {name: dark n stormy, price: 7}
            - {name: hot toddy, price: 10}
            - {name: margarita, price: 10}
            - {name: mimosa jar, price: 25}
            - {name: mimosa, price: 7}
            - {name: mojito, price: 10}
            - {name: moscow mule, price: 10}
            - {name: negroni, price: 12}
            - {name: rum citrus smash, price: 10}
            - {name: (virgin) citrus smash, price: 5}
            - {name: old-fashioned, price: 12}
            - {name: pellegrino, price: 8}
            - {name: rhubarb n rye, price: 12}
            - {name: spanish daisy, price: 10}
            - {name: gimlet, price: 10}
            - {name: french 75, price: 9}
            - {name: martini french, price: 9}
            - {name: special note, add_on_price: 0}
            - {name: tinto de verano, price: 8}
            - {name: bianco spritz, price: 8}
        - name: soft drinks
          items: 
            - {name: coke, price: 3}
            - {name: cran, price: 3}
            - {name: dcoke, price: 3}
            - {name: housemade ginger, price: 5}
            - {name: lemonade, price: 5}
            - {name: OJ, price: 3}
            - {name: pellegrino, price: 4}
            - {name: pineapple, price: 3}
            - {name: seltzer, price: 2}
            - {name: sprite, price: 3}
            - {name: tonic, price: 3}
            - {name: special note, add_on_price: 0}
        - name: spirits
          items: 
            - {name: Absinthe, price: 14}
            - {name: Amaro Lucano, price: 9}
            - {name: Aperol, price: 9}
            - {name: Armagnac, price: 8}
            - {name: Bunnahaiban 12yr, price: 14}
            - {name: Campari, price: 10}
            - {name: Catskill Provisions, price: 11}
            - {name: Chartreaux, price: 23}
            - {name: Cognac, price: 9}
            - {name: Dry Curacao, price: 10}
            - {name: Evan Williams, price: 7}
            - {name: Fernet-Branca Amaro, price: 10}
            - {name: Frangelico, price: 10}
            - {name: Glenlivet, price: 13}
            - {name: Gosling's, price: 8}
            - {name: Gozio, price: 8}
            - {name: Grappa, price: 8}
            - {name: Greenall's Gin, price: 7}
            - {name: Greenhook Gin, price: 10}
            - {name: Holland's Gin, price: 8}
            - {name: Irish Cream Kerrygold, price: 10}
            - {name: Jameson, price: 10}
            - {name: Kahluah, price: 9}
            - {name: Laphroig 10yr, price: 14}
            - {name: Laws Bourbon, price: 14}
            - {name: Maker's Mark, price: 10}
            - {name: Mathilde Raspberry, price: 9}
            - {name: Marca Mezcal, price: 12}
            - {name: Bruxo Mezcal, price: 9}
            - {name: Pine Barrens, price: 19}
            - {name: Pitu, price: 6}
            - {name: Professore, price: 9}
            - {name: Pueblo Anejo, price: 9}
            - {name: Pueblo Blanco, price: 7}
            - {name: Pueblo Reposado, price: 8}
            - {name: Rum-White, price: 8}
            - {name: Sambuca Lucano, price: 8}
            - {name: Scotch Tullibardine, price: 14}
            - {name: Seville Orange, price: 9}
            - {name: Shipwreck Coconut Rum, price: 9}
            - {name: Shipwreck Spiced Rum, price: 9}
            - {name: Sobieski, price: 7}
            - {name: Supercassis, price: 8}
            - {name: Suze, price: 8}
            - {name: Templeton Rye, price: 10}
            - {name: Tito's, price: 8}
           # - {name: Triple Sec, price: 5}
            - {name: Van Gogh Espresso, price: 11}
            - {name: Wathen's Single Barrel Bourbon, price: 10}
            - {name: Whistle Pig, price: 17}
            - {name: special note, add_on_price: 0}
        - name: shots
          items: 
            - {name: Absinthe shot, price: 10}
            - {name: Amaro shot, price: 7}
            - {name: Aperol shot, price: 7}
            - {name: Armagnac snifter, price: 6}
            - {name: Bunnahaiban 12yr shot, price: 10}
            - {name: Campari shot, price: 7}
            - {name: Catskill Provisions shot, price: 8}
            - {name: Chartreaux snifter, price: 15}
            - {name: Coconut Rum shot, price: 6}
            - {name: Cognac snifter, price: 7}
            - {name: Cruzan shot, price: 5}
            - {name: Dry Curacao shot, price: 7}
            - {name: Evan Williams shot, price: 5}
            - {name: Fernet-Branca snifter, price: 7}
            - {name: Frangelico snifter, price: 7}
            - {name: Glenlivet shot, price: 9}
            - {name: Gosling's shot, price: 6}
            - {name: Gozio snifter, price: 6}
            - {name: Grappa snifter, price: 6}
            - {name: Greenall's Gin shot, price: 6}
            - {name: Greenhook Gin shot, price: 8}
            - {name: Holland's Gin shot, price: 6}
            - {name: Irish Cream snifter, price: 7}
            - {name: Jameson shot, price: 7}
            - {name: Kahluah snifter, price: 7}
            - {name: Laphroig 10yr shot, price: 9}
            - {name: Laws Bourbon shot, price: 10}
            - {name: Maker's Mark shot, price: 8}
            - {name: Mathilde Raspberry shot, price: 7}
            - {name: Marca Mezcal shot, price: 9}
            - {name: Bruxo Mezcal shot, price: 7}
            - {name: Pine Barrens shot, price: 13}
            - {name: Pitu shot, price: 5}
            - {name: Professore shot, price: 7}
            - {name: Pueblo Anejo shot, price: 7}
            - {name: Pueblo Blanco shot, price: 6}
            - {name: Pueblo Reposado shot, price: 7}
            - {name: Rum-White shot, price: 6}
            - {name: Sambuca snifter, price: 6}
            - {name: Scotch Tullibardine shot, price: 10}
            - {name: Seville Orange shot, price: 6}
            - {name: Sobieski shot, price: 5}
            - {name: Spiced Rum shot, price: 6}
           # - {name: Supercassis shot, price: 6}
            - {name: Suze snifter, price: 6}
            - {name: Templeton Rye shot, price: 8}
            - {name: Tito's shot, price: 6}
           # - {name: Triple Sec shot, price: 5}
            - {name: Van Gogh Espresso shot, price: 8}
            - {name: Wathen's Bourbon shot, price: 10}
            - {name: Whistle Pig shot, price: 12}
            - {name: special note, add_on_price: 0}
        - name: mixers
          items: 
            - {name: mix tonic, add_on_price: 0}
            - {name: mix coke, add_on_price: 0}
            - {name: mix dcoke, add_on_price: 0}
            - {name: mix ginger, add_on_price: 0}
            - {name: mix cran, add_on_price: 0}
            - {name: mix pineapple, add_on_price: 0}
            - {name: mix seltzer, add_on_price: 0}
            - {name: mix sprite, add_on_price: 0}
            - {name: splash, add_on_price: 0}
            - {name: rocks, add_on_price: 0}
            - {name: big rock, add_on_price: \0}
            - {name: neat, add_on_price: 0}
            - {name: up, add_on_price: 0}
            - {name: lime garnish, add_on_price: 0}
            - {name: lemon garnish, add_on_price: 0}
            - {name: orange garnish, add_on_price: 0}
            - {name: twist, add_on_price: 0}
            - {name: olive garnish, add_on_price: 0}
            - {name: chilled, add_on_price: 0}
            - {name: salt rim, add_on_price: 0}
            - {name: no salt rim, add_on_price: 0}
            - {name: sugar rim, add_on_price: 0}
            - {name: chilled, add_on_price: 0}
            - {name: in old fashioned, add_on_price: 2}
            - {name: in dirty martini, add_on_price: 2}
            - {name: in martini, add_on_price: 2}
            - {name: in manhattan, add_on_price: 2}
            - {name: in margarita, add_on_price: 2}
            - {name: in sour, add_on_price: 2}
            - {name: in spritzer, add_on_price: 1}
            - {name: special note, add_on_price: 0}
    - name: market
      subcategories:
        - name: market 
          items: 
            - {name: market fig, price: 6}
            - {name: market coffe, price: 14}
            - {name: market balsamic, price: 20}
            - {name: market hazelnuts, price: 10}
            - {name: market caperberries, price: 6}
            - {name: market anchovy, price: 3}
            - {name: market special price, price: 0}
