
menu:
  categories:
    - name: tables
      subcategories:
        - name: all
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: 10
            - name: 11
            - name: 12
            - name: 13
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
            - name: O1
            - name: O2
            - name: O3
            - name: O4
            - name: O5
            - name: O6
            - name: O7
            - name: T1 
            - name: T2
            - name: T3
    - name: food
      subcategories:
        - name: guests 
          items: 
            - {name: 1, price: 0}
            - {name: 2, price: 0}
            - {name: 3, price: 0}
            - {name: 4, price: 0}
            - {name: 5, price: 0}
            - {name: 6, price: 0}
            - {name: 7, price: 0}
            - {name: 8, price: 0}
            - {name: 9, price: 0}
            - {name: 10, price: 0}
            - {name: gluten, price: 0}
            - {name: nut, price: 0}
            - {name: shellfish, price: 0}
            - {name: egg, price: 0}
        - name: dinner
          items: 
            - {name: warm olives, price: 5}
            - {name: marcona almonds, price: 5}
            - {name: anchovy, price: 6}
            - {name: caesar salad, price: 9}
            - {name: burrata , price: 14}
            - {name: patatas bravas, price: 6}
            - {name: squash, price: 8}
            - {name: peppers, price: 9}
            - {name: scallops, price: 14}
            - {name: foie gras, price: 16}
            - {name: panini , price: 9}
            - {name: marrow bones, price: 8}
            - {name: pulpo, price: 14}
            - {name: bocadillo, price: 8}
            - {name: sebada, price: 7}
            - {name: tomatillo soup, price: 8}
            - {name: duck, price: 16}
            - {name: beef chorizo, price: 10}
            - {name: chicken, price: 12}
            - {name: bread, price: 3}
        - name: boards
          items: 
            - name: 1-board
              price: 7
            - name: 3-board
              price: 16
            - name: 5-board
              price: 23
            - name: italian board
              price: 27
            - name: spanish board
              price: 27
            - name: mixed cheese board
              price: 27
            - {name: manchego , price: 0}
            - {name: cana de cabra, price: 0}
            - {name: campo de montalban, price: 0}
            - {name: tallegio, price: 0}
            - {name: piave, price: 0}
            - {name: pecorino tartufo, price: 0}
            - {name: daffinois, price: 0}
            - {name: garrotxa, price: 0}
            - {name: blue cheese, price: 0}
            - {name: gruyere, price: 0}
            - {name: cheddar, price: 0}
            - {name: gouda, price: 0}
            - {name: bufala, price: 0}
            #- {name: capri, price: 0}
            - {name: seranno ham, price: 0}
            - {name: lomo, price: 0}
            - {name: chorizo, price: 0}
            - {name: prosciutto, price: 0}
            - {name: hot capicolla, price: 0}
            - {name: felino, price: 0}
            - {name: pata negra, price: 15}
            #- {name: rosette de lyon, price: 0}
            - {name: extra fig, price: 2}
        - name: dessert_etc
          items: 
            - {name: panacotta, price: 7}
            - {name: chocolate, price: 5}
            - {name: apple crisp, price: 7}
            - {name: gift5, price: 5}
            - {name: gift10, price: 10}
            - {name: gift15, price: 15}
            - {name: gift20, price: 20}
            - {name: gift25, price: 25}
            - {name: gift30, price: 30}
            - {name: gift35, price: 35}
            - {name: gift40, price: 40}
            - {name: gift45, price: 45}
            - {name: gift50, price: 50}
            - {name: gift55, price: 55}
            - {name: gift60, price: 60}
            - {name: gift65, price: 65}
            - {name: gift70, price: 70}
            - {name: gift75, price: 75}
            - {name: gift80, price: 80}
            - {name: gift85, price: 85}
            - {name: gift90, price: 90}
            - {name: gift95, price: 95}
            - {name: gift100, price: 100}
            - {name: gift105, price: 105}
            - {name: gift110, price: 110}
            - {name: gift115, price: 115}
            - {name: gift120, price: 120}
            - {name: gift125, price: 125}
            - {name: gift130, price: 130}
            - {name: gift135, price: 135}
            - {name: gift140, price: 140}
            - {name: gift145, price: 145}
            - {name: gift150, price: 150}
            - {name: gift155, price: 155}
            - {name: gift160, price: 160}
            - {name: gift165, price: 165}
            - {name: gift170, price: 170}
            - {name: gift175, price: 175}
            - {name: gift180, price: 180}
            - {name: gift185, price: 185}
            - {name: gift190, price: 190}
            - {name: gift195, price: 195}
            - {name: gift200, price: 200}
            - {name: gift205, price: 205}
            - {name: gift210, price: 210}
            - {name: gift215, price: 215}
            - {name: gift220, price: 220}
            - {name: gift225, price: 225}
            - {name: gift230, price: 230}
            - {name: gift235, price: 235}
            - {name: gift240, price: 240}
            - {name: gift245, price: 245}
            - {name: gift250, price: 250}
        - name: specials
          items: 
            - {name: discount, price: -1}
            - {name: extras, price: 1}
            - {name: gratuity18, price: 0}
            - {name: special price, price: 0}
            - {name: corkage fee, price: 10}
            - {name: corkage, price: 10}
            - {name: special3, price: 3}
            - {name: special4, price: 4}
            - {name: special5, price: 5}
            - {name: special6, price: 6}
            - {name: special7, price: 7}
            - {name: special8, price: 8}
            - {name: special9, price: 9}
            - {name: special10, price: 10}
            - {name: special11, price: 11}
            - {name: special12, price: 12}
            - {name: special13, price: 13}
            - {name: special14, price: 14}
            - {name: special15, price: 15}
            - {name: special16, price: 16}
            - {name: special17, price: 17}
            - {name: special18, price: 18}
            - {name: special19, price: 19}
            - {name: special20, price: 20}
            - {name: special21, price: 21}
            - {name: special22, price: 22}
            - {name: special23, price: 23}
            - {name: special24, price: 24}
            - {name: special25, price: 25}
            - {name: special26, price: 26}
            - {name: special27, price: 27}
            - {name: special28, price: 28}
            - {name: special29, price: 29}
            - {name: special30, price: 30}
            - {name: special31, price: 31}
            - {name: special32, price: 32}
        - name: lunch
          items: 
            - {name: lunch special, price: 9}
            - {name: special tomato soup, price: 0}
            - {name: special mexican soup, price: 0}

            - {name: half prosciutto san, price: 0}
            - {name: half spanish ham and cheese, price: 0}
            - {name: half bean and kraut, price: 0}
            - {name: half bcadillo, price: 0}

            - {name: half taleggio panini, price: 0}
            - {name: half soppresatta panini, price: 0}
            - {name: half copa cubano, price: 0}
            - {name: half goat mush san, price: 0}

            - {name: prosciutto san, price: 10}
            - {name: spanish ham and cheese, price: 9}
            - {name: bean and kraut, price: 7}
            - {name: bcadillo, price: 8}

            - {name: taleggio panini, price: 10}
            - {name: soppresatta panini, price: 7}
            - {name: copa cubano, price: 11}
            - {name: goat mush san, price: 8}
            - {name: fork-mix cesar, price: 9}
            - {name: burrata, price: 14}
            - {name: house salad, price: 8}
            - {name: tomato soup and cheesy toast, price: 6}
            - {name: mexican soup, price: 8}

            - {name: anchovy, price: 6}
            - {name: patatas, price: 6}
            - {name: scallops, price: 14}
            - {name: cebada, price: 7}
            - {name: bread, price: 3}

        - name: market 
          items: 
            - {name: market fig, price: 6}
            - {name: market coffe, price: 14}
            - {name: market balsamic, price: 20}
            - {name: market hazelnuts, price: 10}
            - {name: market caperberries, price: 6}
            - {name: market anchovy, price: 3}
        - name: brunch 
          items: 
            - {name: bloomfield, price: 12}
            - {name: scramble, price: 8}
            - {name: frittata verde, price: 9}
            - {name: french toast, price: 8}
            - {name: bacon, price: 5}
            - {name: taleggio panini, price: 10}
            - {name: sopressata panini, price: 9}
            - {name: copa cubano, price: 11}
            - {name: goat cheese panini, price: 8}
            - {name: fork mix caesar, price: 9}
            - {name: burrata salad, price: 14}
            - {name: house salad, price: 8}
            - {name: smoked anchovies, price: 6}
            - {name: patatas bravas, price: 6}
            - {name: ham cheese toast, price: 8}
            - {name: cebada, price: 7}
            - {name: bocadillo, price: 8}
            - {name: bread, price: 3}
            - {name: coffee, price: 4}
            - {name: decaf, price: 4}
            - {name: english breakfast, price: 4}
            - {name: jasmin tea, price: 4}
            - {name: paris tea, price: 4}
            - {name: chamomile tea, price: 4}
    - name: bev
      subcategories:
        - name: bar
          items: 
            - {name: white sangrea, price: 8}
            - {name: white sangrea jar, price: 32}
            - {name: red sangrea, price: 8}
            - {name: red sangrea jar, price: 32}
            - {name: wine flight, price: 18}
            - {name: pelligrino, price: 3}
            - {name: coffee, price: 4}
            - {name: decaf, price: 4}
            - {name: english breakfast, price: 4}
            - {name: jasmin tea, price: 4}
            - {name: paris tea, price: 4}
            - {name: chamomile tea, price: 4}
            - {name: seltzer, price: 2}
            - {name: coke, price: 3}
            - {name: dcoke, price: 3}
            - {name: lemon, price: 4}
            - {name: ginger, price: 4}
            - {name: blood orange, price: 4}
            - {name: tonic, price: 4}
            - {name: cran, price: 3}
            - {name: oj, price: 3}
            - {name: rickey, price: 5}
            - {name: lemonade, price: 5}
            - {name: citrus smash (virgin), price: 5}
            - {name: cktail of the day, price: 12}
            - {name: cktail7, price: 7}
            - {name: cktail10, price: 10}
            - {name: cktail12, price: 12}
            - {name: cktail14, price: 14}
            - {name: vodka tonic, price: 7}
            - {name: vodka cran, price: 7}
            - {name: vodka sprite, price: 7}
            - {name: vodka soda, price: 7}
            - {name: rum coke, price: 7}
            - {name: dark n stormy, price: 7}
            - {name: wine spritz, price: 10}
            - {name: old-fashioned, price: 12}
            - {name: manhattan, price: 12}
            - {name: martini, price: 10}
            - {name: drty mart, price: 10}
            - {name: cosmo, price: 10}
            - {name: margarita, price: 10}
            - {name: caipirnha, price: 10}
            - {name: ciirus smash rum, price: 10}
            - {name: burbon coke, price: 10}
            - {name: patron shot, price: 10}
            - {name: pueblo shot, price: 10}
            - {name: vodka shot, price: 7}
            - {name: sambucca shot, price: 7}
            - {name: frangelico shot, price: 7}
            - {name: spiked thai tea, price: 7}
            - {name: hot toddy, price: 7}
            - {name: belini, price: 7}
            - {name: belini jar, price: 23}
            - {name: mimosa, price: 7}
            - {name: mimosa jar, price: 23}
            - {name: bloody maria, price: 7}
            - {name: bloody maria jar, price: 23}
