#server side settings
db:
  name: plansrv

paystub_buss_info_line: "PLANCHA dba Infrared Enterprises 931 Franklin AVE, GardenCity, NY 516-246-9459"
#"HAL Corp. Riverdale"
#"SALUMI dba Ultraviolet Enterprises 5600 Merrick RD, Massapequa, NY 11758 516-620-0057"

guest_check_header: "PLANCHA\n931 Franklin Avenue\nGarden City, NY\n516-246-9459"
#"HALUMI\nRiverndale Run\nThe Massapequas\n516-555-5557"
#"SALUMI\n5600 Merrick Rd Massapequa\n516-620-0057"

new_page_for_white_wine: true
use_wine_fun: true

coupon:
  #filename: /var/www/coupon.pdf


style:
  backgroundColor: "#f0c040"
  #backgroundImage: "url(http://fullhdwallpapers.ru/image/flags/17421/flag-ssha-granzh.jpg)"
  #backgroundImage: "url(http://specsrv.barplancha.com:/resources/redgoldstars.jpg)"

printer:
  ipaddr: 192.168.1.151
  devid: local_printer
  timeout: 30000

web_menu_filename: "/var/www/planchaweb/menu"

menu:
  supercategories:
    - name: tables
      categories:
        - name: floor
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: 10
            - name: 11
            - name: 12
            - name: 13
            - name: X9
        - name: bar
          items: 
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
        - name: other
          items: 
            - name: O1
            - name: O2
            - name: O3
            - name: O4
            - name: O5
            - name: O6
            - name: O7
            - name: O8
            - name: O9
            - name: O10
            - name: O11
            - name: O12
            - name: O13
            - name: O14
            - name: O15
            - name: D1
            - name: D2
            - name: D3
            - name: D4
            - name: D5
            - name: D6
            - name: D7
            - name: D8
            - name: D9
            - name: TEST1
            - name: TEST2
            - name: Tran Tobin 
        - name: takeout
          items: 
            - name: T1 
            - name: T2
            - name: T3
            - name: T4
            - name: T5
   # - name: NYE
   #   subcategories:
   #     - name: ala carte
   #       items: 
   #         - {name: charcuterie plate, price: 24}
   #         - {name: oyster mushrooms, price: 13}
   #         - {name: winter salad, price: 12}
   #         - {name: crudo, price: 15}
   #         - {name: prawns, price: 16}
   #         - {name: sunchoke, price: 12}
   #         - {name: cauliflower, price: 11}
   #         - {name: pate, price: 13}
   #         - {name: foie gras, price: 15}
   #         - {name: escargot, price: 14}
   #         - {name: iberico, price: 22}
   #         - {name: short rib, price: 21}
   #         - {name: panatone, price: 8}
