
menu:
  categories:
    - name: tables
      subcategories:
        - name: floor
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: 10
            - name: 11
            - name: 12
            - name: 13
        - name: bar
          items: 
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
        - name: other
          items: 
            - name: O1
            - name: O2
            - name: O3
            - name: O4
            - name: O5
            - name: O6
            - name: O7
        - name: takeout
          items: 
            - name: T1 
            - name: T2
            - name: T3
            - name: T4
            - name: T5
    - name: food
      subcategories:
        - name: dinner
          items: 
            - {name: warm olives, price: 5}
            - {name: marcona almonds, price: 5}
            - {name: anchovy, price: 6}
            - {name: caesar , price: 9}
            - {name: burrata , price: 14}
            - {name: patatas bravas, price: 6}
            - {name: sprouts, price: 8}
            - {name: peppers, price: 9}
            - {name: scallops, price: 14}
            - {name: foie gras, price: 16}
            - {name: panini , price: 9}
            - {name: marrow bones, price: 8}
            - {name: pulpo, price: 14}
            - {name: bocadillo, price: 8}
            - {name: cebada, price: 10}
            - {name: celery root soup, price: 8}
            - {name: duck, price: 16}
            - {name: beef chorizo, price: 10}
            - {name: lamb, price: 21}
            - {name: panacotta, price: 7}
            - {name: chocolate, price: 5}
            - {name: apple crisp, price: 7}
            - {name: special, price: 0}
            - {name: bread, price: 3}
        - name: boards
          items: 
            - name: 1-board
              price: 7
            - name: 3-board
              price: 16
            - name: 5-board
              price: 23
            - name: 6-board
              price: 27
            - name: italian board
              price: 27
            - name: spanish board
              price: 27
            - name: mixed cheese board
              price: 27
            - {name: manchego , price: 0}
            - {name: cana de cabra, price: 0}
            - {name: campo de montalban, price: 0}
            - {name: tallegio, price: 0}
            - {name: piave, price: 0}
            - {name: pecorino tartufo, price: 0}
            - {name: daffinois, price: 0}
            - {name: garrotxa, price: 0}
            - {name: blue cheese, price: 0}
            #- {name: gruyere, price: 0}
            - {name: surchoix, price: 0}
            - {name: gouda, price: 0}
            #- {name: capri, price: 0}
            - {name: seranno ham, price: 0}
            - {name: lomo, price: 0}
            - {name: chorizo, price: 0}
            - {name: prosciutto, price: 0}
            - {name: hot capicolla, price: 0}
            - {name: felino, price: 0}
            - {name: pata negra, price: 15}
            #- {name: rosette de lyon, price: 0}
            - {name: extra fig, price: 2}
            - name: add-on
              price: 5
            - name: to-go-on-board
              price: 0
        - name: allergy
          items: 
            - {name: gluten, price: 0}
            - {name: nut, price: 0}
            - {name: shellfish, price: 0}
            - {name: egg, price: 0}
        - name: misc
          items: 
            - {name: gift, price: 50}
            - {name: gratuity18, price: 18}
            - {name: gratuity20, price: 20}
            - {name: gratuity special, price: 0}
            - {name: tax-free special, price: 0}
            - {name: corkage fee, price: 10}
        - name: lunch
          items: 
            - {name: american burger, price: 14}
            - {name: spanish burger, price: 13}
            - {name: italian burger, price: 13}
            #- {name: lunch special, price: 9}
            #- {name: special tomato soup, price: 0}

            #- {name: half prosciutto san, price: 0}
            #- {name: half spanish ham and cheese, price: 0}
            #- {name: half eggplant, price: 0}
            #- {name: half bcadillo, price: 0}

            #- {name: half taleggio panini, price: 0}
            #- {name: half soppresatta panini, price: 0}
            #- {name: half copa cubano, price: 0}
            #- {name: half goat mush san, price: 0}

            - {name: prosciutto san, price: 10}
            - {name: spanish ham and cheese, price: 9}
            - {name: eggplant, price: 7}
            - {name: bocadillo, price: 8}

            - {name: taleggio panini, price: 10}
            - {name: soppresatta panini, price: 7}
            - {name: copa cubano, price: 11}
            - {name: goat mush san, price: 8}
            - {name: beet and bleu, price: 9}
            - {name: burrata, price: 14}
            - {name: house salad, price: 8}
            - {name: tomato soup and cheesy toast, price: 6}
            - {name: celery root soup, price: 8}

            - {name: anchovy, price: 6}
            - {name: patatas, price: 6}
            - {name: scallops, price: 14}
            - {name: cebada, price: 7}
            - {name: bread, price: 3}
        - name: brunch 
          items: 
            - {name: bloomfield, price: 12}
            - {name: scramble, price: 8}
            - {name: frittata verde, price: 9}
            - {name: french toast, price: 8}
            - {name: bacon, price: 5}
            - {name: taleggio panini, price: 10}
            - {name: sopressata panini, price: 9}
            - {name: copa cubano, price: 11}
            - {name: goat cheese panini, price: 8}
            - {name: beet and bleu, price: 9}
            - {name: burrata salad, price: 14}
            - {name: house salad, price: 8}
            - {name: smoked anchovies, price: 6}
            - {name: patatas bravas, price: 6}
            - {name: ham cheese toast, price: 8}
            - {name: cebada, price: 7}
            - {name: bocadillo, price: 8}
            - {name: bread, price: 3}
            - {name: coffee, price: 4}
            - {name: decaf, price: 4}
            - {name: iced tea, price: 3}
            - {name: english breakfast, price: 4}
            - {name: jasmin tea, price: 4}
            - {name: paris tea, price: 4}
            - {name: chamomile tea, price: 4}
    - name: bev
      subcategories:
        - name: bar
          items: 
            - {name: amaro, price: 4}
            - {name: red sangrea jar, price: 28}
            - {name: red sangrea, price: 8}
            - {name: white sangrea jar, price: 28}
            - {name: white sangrea, price: 8}
            - {name: rose sangrea jar, price: 28}
            - {name: rose sangrea, price: 8}
            - {name: belini jar, price: 23}
            - {name: belini, price: 7}
            - {name: blood orange, price: 4}
            - {name: bloody maria jar, price: 23}
            - {name: bloody maria, price: 7}
            - {name: burbon coke, price: 10}
            - {name: caipirnha, price: 10}
            - {name: ciirus smash rum, price: 10}
            - {name: citrus smash (virgin), price: 5}
            - {name: cktail10, price: 10}
            - {name: cktail12, price: 12}
            - {name: cktail14, price: 14}
            - {name: cktail7, price: 7}
            - {name: cktail5, price: 5}
            - {name: cktail of the day, price: 12}
            - {name: coffee, price: 4}
            - {name: coke, price: 3}
            - {name: cosmo, price: 10}
            - {name: cran, price: 3}
            - {name: dark n stormy, price: 7}
            - {name: dcoke, price: 3}
            - {name: decaf, price: 4}
            - {name: english breakfast, price: 4}
            - {name: frangelico shot, price: 7}
            - {name: ginger, price: 4}
            - {name: hot toddy, price: 7}
            - {name: lemonade, price: 5}
            - {name: lemon, price: 4}
            - {name: liquor flight, price: 20}
            - {name: manhattan, price: 12}
            - {name: margarita, price: 10}
            - {name: martini, price: 10}
            - {name: martini classic, price: 10}
            - {name: martini dirty, price: 10}
            - {name: mimosa jar, price: 23}
            - {name: mimosa, price: 7}
            - {name: oj, price: 3}
            - {name: old-fashioned, price: 12}
            - {name: patron shot, price: 10}
            - {name: pelligrino, price: 3}
            - {name: pueblo shot, price: 10}
            - {name: red sangrea jar, price: 32}
            - {name: red sangrea, price: 8}
            - {name: rickey, price: 5}
            - {name: rum coke, price: 7}
            - {name: sambucca shot, price: 7}
            - {name: seltzer, price: 2}
            - {name: shirly temple, price: 5}
            - {name: tonic, price: 4}
            - {name: spiked thai tea, price: 7}
            - {name: tea jasmin, price: 4}
            - {name: tea chamomile, price: 4}
            - {name: tea paris, price: 4}
            - {name: tea iced, price: 3}
            - {name: virgin5, price: 5}
            - {name: vodka cran, price: 7}
            - {name: vodka shot, price: 7}
            - {name: vodka soda, price: 7}
            - {name: vodka sprite, price: 7}
            - {name: vodka tonic, price: 7}
            - {name: white sangrea jar, price: 32}
            - {name: white sangrea, price: 8}
            - {name: wine flight, price: 16}
            - {name: wine spritz, price: 10}
    - name: market
      subcategories:
        - name: market 
          items: 
            - {name: market fig, price: 6}
            - {name: market coffe, price: 14}
            - {name: market balsamic, price: 20}
            - {name: market hazelnuts, price: 10}
            - {name: market caperberries, price: 6}
            - {name: market anchovy, price: 3}
            - {name: market special price, price: 0}
