style:
  backgroundColor: "#f0c040"
  #backgroundImage: "url(http://fullhdwallpapers.ru/image/flags/17421/flag-ssha-granzh.jpg)"

coupon:
  #filename: /var/www/coupon.pdf

menu:
  categories:
    - name: tables
      subcategories:
        - name: floor
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: 10
            - name: 11
            - name: 12
            - name: 13
        - name: bar
          items: 
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
        - name: other
          items: 
            - name: O1
            - name: O2
            - name: O3
            - name: O4
            - name: O5
            - name: O6
            - name: O7
            - name: TEST1
            - name: TEST2
        - name: takeout
          items: 
            - name: T1 
            - name: T2
            - name: T3
            - name: T4
            - name: T5
   # - name: NYE
   #   subcategories:
   #     - name: ala carte
   #       items: 
   #         - {name: charcuterie plate, price: 24}
   #         - {name: oyster mushrooms, price: 13}
   #         - {name: winter salad, price: 12}
   #         - {name: crudo, price: 15}
   #         - {name: prawns, price: 16}
   #         - {name: sunchoke, price: 12}
   #         - {name: cauliflower, price: 11}
   #         - {name: pate, price: 13}
   #         - {name: foie gras, price: 15}
   #         - {name: escargot, price: 14}
   #         - {name: iberico, price: 22}
   #         - {name: short rib, price: 21}
   #         - {name: panatone, price: 8}
