db:
  name: salsrv

#paystub_buss_info_line: "HAL Corp. Riverdale"
paystub_buss_info: 
  - "SALUMI dba Ultraviolet Enterprises"
  - "5600 Merrick RD, Massapequa, NY 11758"
  - "516-620-0057"

#paystub_buss_info_line: "PLANCHA dba Infrared Enterprises 931 Franklin AVE, GardenCity, NY 516-246-9459"

#guest_check_header: "HALUMI\nRiverndale Run\nThe Massapequas\n516-555-5557"
guest_check_header: "SALUMI\n5600 Merrick Rd Massapequa\n516-620-0057"
#guest_check_header: "PLANCHA\n931 Franklin Avenue\nGarden City, NY\n516-246-9459"

new_page_for_white_wine: false #plancha true
use_wine_fun: false #plancha true

coupon:
  #filename: /var/www/coupon.pdf

post_it_note: Watch this space!

happy_hour:
  start: 12
  end: 18
  discount: .5

printer:
  type: webprint
  web_print_service_url: "http://old.salumibarli.com:3681/iprint.py"
  web_print_image_service_url: "http://old.salumibarli.com:3681/iprint.py/print_url"
  timeout: 3000

#autoprint_png: salumiqrmenu


portal_url: "https://sites.google.com/view/salumi/p-o-r-t-a-l"
#portal_url: "http://sites.google.com/view/plancha/portal"

style:
  backgroundColor: "#2020f0"
  #backgroundImage: "url(http://alpinebakeryandtrattoria.com/wp-content/uploads/2015/12/new-years-eve-alpine.jpg)"
  #backgroundImage: "url(http://salumibarli.com:3681/resources/snowflake.jpg)"

web_menu_filename: "/var/www/salumiweb/menu"

menu:
  supercategories:
    - name: tables
      categories:
        - name: market
          items: 
            - name: MKT 
            - name: M1 
            - name: Couch1 
            - name: Couch2 
            - name: M1.1
            - name: M1.2
            - name: M1.3
            - name: M2.1
            - name: M2.2
            - name: M2.3
            - name: M3.1
            - name: M3.2
            - name: M3.3
            - name: M4.1
            - name: M4.2
            - name: M4.3
            - name: M5
            - name: M6
            - name: M7
            - name: M8
            - name: M9
        - name: waiting
          items: 
            - name: W1
            - name: W2
            - name: W3
            - name: W4
            - name: W5
            - name: W6
            - name: W7
            - name: W8
            - name: W9
            - name: W10
            - name: W11
            - name: W12
            - name: W13
            - name: W14
            - name: W15
        - name: outside
          items: 
            - name: O1 
            - name: O2
            - name: O3
            - name: O4
            - name: O5
            - name: O6
            - name: O7
            - name: O8
            - name: O9
            - name: O10
            - name: O11
            - name: O12
            - name: O13
            - name: O14
            - name: O15
        - name: takeout
          items: 
            - name: T1 
            - name: T2 
            - name: T3 
            - name: T4 
            - name: T5 
            - name: T6 
            - name: T7 
            - name: T8 
            - name: T9 
            - name: T10 
            - name: T11 
            - name: T12
            - name: T13
            - name: T14
            - name: T15
            - name: T16
            - name: T17
            - name: T18
            - name: T19
            - name: T20
            - name: T21
            - name: T22
            - name: T23
            - name: T24
            - name: T25
            - name: T26
            - name: T27
            - name: T28
            - name: T29
            - name: T30
            - name: T31
            - name: T32
            - name: T33
            - name: T34
            - name: T35
            - name: T36
            - name: T37
            - name: T38
            - name: T39
            - name: T40
            - name: T41 
            - name: T42
            - name: T43
            - name: T44
            - name: T45
            - name: T46
            - name: T47
            - name: T48
            - name: T49
            - name: T50
            - name: T51
            - name: T52
            - name: T53
            - name: T54
            - name: T55
            - name: T56
            - name: T57
            - name: T58
            - name: T59
            - name: T60
            - name: T61
            - name: T62
            - name: T63
            - name: T64
            - name: T65
            - name: T66
            - name: T67
            - name: T68
            - name: T69
            - name: T70
            - name: T71
            - name: T72
            - name: T73
            - name: T74
            - name: T75
            - name: T76
            - name: T77
            - name: T78
            - name: T79
            - name: T80
            - name: TEST
            - name: TEST2
        - name: resys
          items: 
            - name: R1
            - name: R2
            - name: R3
            - name: R4
            - name: R5
            - name: R6
            - name: R7
            - name: R8
            - name: R10
            - name: R11
            - name: R12
            - name: R13
        - name: floor
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: F1
            - name: F2
            - name: F3
            - name: F4
            - name: F5
        - name: bar
          items: 
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
            - name: B14
            - name: B15
            - name: B16
            - name: B17
