style:
  backgroundColor: gray
  backgroundImage: "url(http://alpinebakeryandtrattoria.com/wp-content/uploads/2015/12/new-years-eve-alpine.jpg)"

menu:
  categories:
    - name: tables
      subcategories:
        - name: market
          items: 
            - name: MKT 
            - name: Couch1 
            - name: Couch2 
            - name: M1 
            - name: M1.1
            - name: M1.2
            - name: M1.3
            - name: M2.1
            - name: M2.2
            - name: M2.3
            - name: M3.1
            - name: M3.2
            - name: M3.3
            - name: M4.1
            - name: M4.2
            - name: M4.3
            - name: M5
            - name: M6
            - name: M7
            - name: M8
            - name: M9
        - name: waiting
          items: 
            - name: W1
            - name: W2
            - name: W3
            - name: W4
            - name: W5
            - name: W6
            - name: W7
            - name: W8
            - name: W9
            - name: W10
            - name: W11
            - name: W12
        - name: takeout
          items: 
            - name: O1 
            - name: O2
            - name: O3
            - name: T1 
            - name: T2 
            - name: T3 
            - name: TEST
        - name: floor
          items: 
            - name: 1
            - name: 2
            - name: 3
            - name: 4
            - name: 5
            - name: 6
            - name: 7
            - name: 8
            - name: 9
            - name: F1
            - name: F2
            - name: F3
            - name: F4
            - name: F5
        - name: bar
          items: 
            - name: B1
            - name: B2
            - name: B3
            - name: B4
            - name: B5
            - name: B6
            - name: B7
            - name: B8
            - name: B9
            - name: B10
            - name: B11
            - name: B12
            - name: B13
            - name: B14
            - name: B15
            - name: B16
            - name: B17
